// Generated by CoffeeScript 1.9.1
(function() {
  var Client, _, apiClient;

  _ = require('underscore');

  apiClient = require('./api_client');

  Client = (function() {
    function Client(options) {
      this.api = new apiClient.APIClient(options);
    }

    Client.prototype.codesList = function(options, cb) {
      return this.api.codesList(options, function(error, body) {
        if (error == null) {
          return cb(error, body.codes);
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.codesGet = function(codeId, cb) {
      return this.api.codesGet(codeId, function(error, body) {
        if (error == null) {
          return cb(error, body);
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.codesDelete = function(codeId, cb) {
      return this.api.codesDelete(codeId, function(error, body) {
        if (error == null) {
          return cb(error, body);
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.codesRevisions = function(codeId, options, cb) {
      return this.api.codesRevisions(codeId, options, function(error, body) {
        if (error == null) {
          return cb(error, body.revisions);
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.codesDownload = function(codeId, options, cb) {
      return this.api.codesDownload(codeId, options, function(error, body) {
        if (error == null) {
          return cb(error, body);
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.tasksList = function(options, cb) {
      return this.api.tasksList(options, function(error, body) {
        if (error == null) {
          return cb(error, body.tasks);
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.tasksGet = function(taskId, cb) {
      return this.api.tasksGet(taskId, function(error, body) {
        if (error == null) {
          return cb(error, body);
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.tasksCreate = function(codeName, params, options, cb) {
      var payload;
      payload = '';
      if (typeof params === 'string') {
        payload = params;
      } else {
        payload = JSON.stringify(params);
      }
      return this.api.tasksCreate(codeName, payload, options, function(error, body) {
        if (error == null) {
          return cb(error, body.tasks[0]);
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.tasksRetry = function(taskId, delay, cb) {
      return this.api.tasksRetry(taskId, delay, function(error, body) {
        if (error == null) {
          return cb(error, body);
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.tasksCancel = function(taskId, cb) {
      return this.api.tasksCancel(taskId, function(error, body) {
        if (error == null) {
          return cb(error, body);
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.tasksCancelAll = function(codeId, cb) {
      return this.api.tasksCancelAll(codeId, function(error, body) {
        if (error == null) {
          return cb(error, body);
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.tasksLog = function(taskId, cb) {
      return this.api.tasksLog(taskId, function(error, body) {
        if (error == null) {
          return cb(error, body);
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.tasksSetProgress = function(taskId, options, cb) {
      return this.api.tasksSetProgress(taskId, options, function(error, body) {
        if (error == null) {
          return cb(error, body);
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.tasksWaitFor = function(taskId, options, cb) {
      var sleep, tasksWaitForBind;
      tasksWaitForBind = _.bind(this.tasksWaitFor, this);
      sleep = options.sleep;
      if (sleep == null) {
        sleep = 5;
      }
      return this.tasksGet(taskId, function(error, body) {
        if (error == null) {
          if (body.status === 'queued' || body.status === 'running') {
            return _.delay(tasksWaitForBind, sleep * 1000, taskId, options, cb);
          } else {
            return cb(error, body);
          }
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.tasksWaitForLog = function(taskId, options, cb) {
      var tasksWaitForLogBind;
      tasksWaitForLogBind = _.bind(this.tasksWaitForLog, this);
      if (options.sleep == null) {
        options.sleep = 5;
      }
      return this.tasksLog(taskId, function(error, body) {
        if (error && error.message.match(/log/i)) {
          return _.delay(tasksWaitForLogBind, options.sleep * 1000, taskId, options, cb);
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.schedulesList = function(options, cb) {
      return this.api.schedulesList(options, function(error, body) {
        if (error == null) {
          return cb(error, body.tasks);
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.schedulesGet = function(scheduleId, cb) {
      return this.api.schedulesGet(scheduleId, function(error, body) {
        if (error == null) {
          return cb(error, body);
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.schedulesCreate = function(codeName, params, options, cb) {
      var payload;
      payload = '';
      if (typeof params === 'string') {
        payload = params;
      } else {
        payload = JSON.stringify(params);
      }
      return this.api.schedulesCreate(codeName, payload, options, function(error, body) {
        if (error == null) {
          return cb(error, body.schedules[0]);
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.schedulesCancel = function(scheduleId, cb) {
      return this.api.schedulesCancel(scheduleId, function(error, body) {
        if (error == null) {
          return cb(error, body);
        } else {
          return cb(error, body);
        }
      });
    };

    Client.prototype.codesUpload = function(name, destination, fileName, cb) {
      var AdmZip, api, fs, ncp, needle, zip;
      needle = require("needle");
      ncp = require("ncp").ncp;
      fs = require("fs");
      AdmZip = require("adm-zip");
      zip = new AdmZip();
      if (destination.charAt(destination.length - 1) !== "/") {
        destination += "/";
      }
      api = this.api;
      ncp.limit = 16;
      return ncp("upload_files", destination, function(err) {
        if (err) {
          throw err;
        }
        return fs.appendFile(destination + "__runner__.sh", "\nnode " + fileName, function(err) {
          var params;
          if (err) {
            throw err;
          }
          zip.addLocalFolder(destination);
          params = {
            data: JSON.stringify({
              name: name,
              file_name: "__runner__.sh",
              runtime: "sh",
              content_type: "text/plain"
            }),
            file: {
              buffer: zip.toBuffer(),
              content_type: "application/zip"
            }
          };
          return api.codesUpload(params, function(err, body) {
            if (err == null) {
              return cb(err, body);
            } else {
              return cb(err, body);
            }
          });
        });
      });
    };

    return Client;

  })();

  module.exports.Client = Client;

}).call(this);
