// Generated by CoffeeScript 1.9.1
(function() {
  var _, config, params, parseCLIData, task_id;

  _ = require('underscore');

  params = null;

  task_id = null;

  config = null;

  parseCLIData = function() {
    var fs, querystring;
    fs = require('fs');
    querystring = require('querystring');
    return process.argv.forEach(function(val, index, array) {
      var e, parsed;
      if (val === "-payload") {
        params = fs.readFileSync(process.argv[index + 1], 'utf8');
        try {
          params = JSON.parse(params);
        } catch (_error) {
          e = _error;
          try {
            parsed = querystring.parse(params);
            if (!(Object.keys(parsed).length === 1 && parsed[Object.keys(parsed)[0]] === '')) {
              params = parsed;
            }
          } catch (_error) {
            e = _error;
          }
        }
      }
      if (val === "-config") {
        config = fs.readFileSync(process.argv[index + 1], 'utf8');
        try {
          config = JSON.parse(config);
        } catch (_error) {
          e = _error;
        }
      }
      if (val === "-id") {
        return task_id = process.argv[index + 1];
      }
    });
  };

  module.exports.params = function() {
    if (!params) {
      parseCLIData();
    }
    return params;
  };

  module.exports.taskId = function() {
    if (!task_id) {
      parseCLIData();
    }
    return task_id;
  };

  module.exports.config = function() {
    if (!config) {
      parseCLIData();
    }
    return config;
  };

}).call(this);
